<Project Sdk="Microsoft.NET.Sdk.Web">
  <!--
    A API é o "Composition Root": o ÚNICO lugar que conhece todas as camadas e liga as peças (Injeção de Dependência).
    Fora daqui, nenhuma classe faz `new` de dependências concretas.
  -->
  <ItemGroup>
    <ProjectReference Include="..\Loja.Application\Loja.Application.csproj" />
    <ProjectReference Include="..\Loja.Infrastructure\Loja.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>
</Project>
